version: '3.8'

services:
  # Basic SNMP agent for baseline testing
  mock-snmp-basic:
    build:
      context: .
      dockerfile: Dockerfile.enhanced
    container_name: mock-snmp-basic
    ports:
      - "11611:11611/udp"
    volumes:
      - ./logs:/app/logs
      - ./metrics:/app/metrics
    command: ["mock-snmp-agent", "--port", "11611", "--host", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "snmpget", "-v2c", "-c", "public", "-t", "3", "localhost:11611", "1.3.6.1.2.1.1.1.0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Delay simulation testing
  mock-snmp-delay:
    build:
      context: .
      dockerfile: Dockerfile.enhanced
    container_name: mock-snmp-delay
    ports:
      - "11612:11612/udp"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    command: ["mock-snmp-agent", "--delay", "500", "--port", "11612", "--host", "0.0.0.0"]
    healthcheck:
      test: ["CMD", "snmpget", "-v2c", "-c", "public", "-t", "5", "localhost:11612", "1.3.6.1.2.1.1.1.0"]
      interval: 45s
      timeout: 15s
      retries: 2

  # Drop rate simulation testing
  mock-snmp-drops:
    build:
      context: .
      dockerfile: Dockerfile.enhanced
    container_name: mock-snmp-drops
    ports:
      - "11613:11613/udp"
    volumes:
      - ./logs:/app/logs
    command: ["mock-snmp-agent", "--drop-rate", "20", "--port", "11613", "--host", "0.0.0.0"]

  # Comprehensive testing with config file
  mock-snmp-comprehensive:
    build:
      context: .
      dockerfile: Dockerfile.enhanced
    container_name: mock-snmp-comprehensive
    ports:
      - "11614:11614/udp"
    volumes:
      - ./logs:/app/logs
      - ./metrics:/app/metrics
      - ./config:/app/config
    command: ["mock-snmp-agent", "--config", "config/comprehensive.yaml", "--port", "11614", "--host", "0.0.0.0"]
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "snmpget", "-v2c", "-c", "public", "-t", "5", "localhost:11614", "1.3.6.1.2.1.1.1.0"]
      interval: 60s
      timeout: 20s
      retries: 2

  # Counter wrap testing
  mock-snmp-counters:
    build:
      context: .
      dockerfile: Dockerfile.enhanced
    container_name: mock-snmp-counters
    ports:
      - "11615:11615/udp"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    command: ["mock-snmp-agent", "--config", "config/counter_wrap_test.yaml", "--port", "11615", "--host", "0.0.0.0"]
    environment:
      - PYTHONPATH=/app

  # Test client for automated testing
  test-client:
    build:
      context: .
      dockerfile: Dockerfile.enhanced
    container_name: snmp-test-client
    depends_on:
      - mock-snmp-basic
      - mock-snmp-delay
      - mock-snmp-drops
      - mock-snmp-comprehensive
      - mock-snmp-counters
    volumes:
      - ./tests:/app/tests
      - ./examples:/app/examples
      - ./logs:/app/logs
    command: ["sleep", "3600"]  # Keep container running for manual tests
    environment:
      - PYTHONPATH=/app

networks:
  default:
    name: mock-snmp-test
