# Enhanced Simulation Configuration
# Demonstrates AgentX-style delays, SNMPv3 contexts, and MIB boundary responses

simulation:
  # AgentX-style subagent delays
  agentx_simulation:
    enabled: true
    registration_delays: true
    registration_delay_ms: 1500
    registration_timeout_rate: 8  # 8% of requests trigger registration delay
    
    master_agent_delays: true
    base_delay_ms: 100
    timeout_threshold_ms: 5000
    
    # Different delays by MIB subsystem (AgentX subagent pattern)
    subagent_delays:
      "1.3.6.1.2.1.1": 50        # System agent - fast
      "1.3.6.1.2.1.2": 200       # Interface agent - medium
      "1.3.6.1.2.1.4": 300       # IP agent - medium
      "1.3.6.1.2.1.25": 800      # Host resources - slow
      "1.3.6.1.2.1.47": 600      # Entity MIB - slow
      "1.3.6.1.4.1": 1200        # Enterprise MIBs - very slow
    
    connection_failures: true
    disconnection_rate: 3        # 3% chance of subagent disconnection
    reconnection_delay_ms: 2000

  # SNMPv3 Context handling
  snmpv3_contexts:
    enabled: true
    
    contexts:
      # VRF contexts
      - name: "vrf-management"
        description: "Management VRF routing instance"
        oid_mappings:
          "1.3.6.1.2.1.1.1.0": "Management VRF Router"
          "1.3.6.1.2.1.1.5.0": "mgmt-router-01"
          "1.3.6.1.2.1.1.6.0": "Management Network"
          "1.3.6.1.2.1.4.1.0": "1"  # IP forwarding enabled
        allowed_users: ["admin", "operator", "monitor"]
        access_level: "read"
      
      - name: "vrf-customer-a"
        description: "Customer A VRF instance"
        oid_mappings:
          "1.3.6.1.2.1.1.1.0": "Customer A Router Instance"
          "1.3.6.1.2.1.1.5.0": "customer-a-pe-01"
          "1.3.6.1.2.1.1.6.0": "Customer A Edge"
          "1.3.6.1.2.1.4.1.0": "1"
        allowed_users: ["customer-a", "operator"]
        access_level: "read"
      
      # Bridge domain contexts
      - name: "bridge-domain-100"
        description: "VLAN 100 bridge domain"
        oid_mappings:
          "1.3.6.1.2.1.1.1.0": "Switch Bridge VLAN 100"
          "1.3.6.1.2.1.1.5.0": "switch-vlan100"
          "1.3.6.1.2.1.17.1.1.0": "6"   # Bridge base num ports
          "1.3.6.1.2.1.17.1.2.0": "2"   # Transparent bridge
        allowed_users: ["switch-admin", "monitor"]
        access_level: "read"
      
      # Firewall context with restrictions
      - name: "firewall-zone-dmz"
        description: "DMZ firewall zone"
        oid_mappings:
          "1.3.6.1.2.1.1.1.0": "Firewall DMZ Zone"
          "1.3.6.1.2.1.1.5.0": "fw-dmz-01"
          "1.3.6.1.2.1.1.6.0": "DMZ Network Segment"
        allowed_users: ["security-admin", "monitor"]
        restricted_oids: ["1.3.6.1.4.1"]  # Block enterprise MIBs
        access_level: "read"

  # MIB boundary responses
  mib_boundaries:
    enabled: true
    
    # EndOfMibView configuration
    end_of_mib_view:
      enabled: true
      mib_view_boundaries:
        "1.3.6.1.2.1.1": "1.3.6.1.2.1.1.9.0"      # System group ends
        "1.3.6.1.2.1.2.2.1": "1.3.6.1.2.1.2.2.1.22" # Interface table ends
        "1.3.6.1.2.1.4": "1.3.6.1.2.1.4.34"        # IP group ends
        "1.3.6.1.2.1.25": "1.3.6.1.2.1.25.7"       # Host resources ends
    
    # NoSuchObject simulation
    no_such_object:
      enabled: true
      missing_objects:
        - "1.3.6.1.2.1.1.8.0"     # System services (often unimplemented)
        - "1.3.6.1.2.1.4.12.0"    # IP forwarding timeout
        - "1.3.6.1.2.1.6.14.0"    # TCP max connections
        - "1.3.6.1.2.1.25.3.8"    # Host disk access
      missing_object_patterns:
        - "1.3.6.1.2.1.10"        # Transmission group
        - "1.3.6.1.2.1.13"        # AppleTalk (obsolete)
        - "1.3.6.1.4.1.99999"     # Non-existent enterprise
    
    # NoSuchInstance simulation (sparse tables)
    no_such_instance:
      enabled: true
      sparse_tables:
        "1.3.6.1.2.1.2.2.1": [3, 5, 7, 9, 11]      # Missing interface indices
        "1.3.6.1.2.1.4.20.1": [2, 4, 6]            # Missing IP address entries
        "1.3.6.1.2.1.4.21.1": [1, 3, 5, 8, 10]     # Missing route entries
    
    # Random boundary injection for stress testing
    random_boundaries: false
    boundary_injection_rate: 5  # 5% when enabled

  # Additional simulation behaviors
  behaviors:
    # Basic delay simulation (combined with AgentX delays)
    delay:
      enabled: true
      global_delay: 0           # AgentX simulation handles delays
      deviation: 50             # Small random variation
    
    # Packet loss simulation
    packet_loss:
      enabled: true
      drop_rate: 2              # 2% packet loss
    
    # Counter progression
    counter_progression:
      enabled: true
      counters:
        "1.3.6.1.2.1.2.2.1.10.1": 1000    # Interface 1 input - 1KB/s
        "1.3.6.1.2.1.2.2.1.16.1": 800     # Interface 1 output - 800B/s
        "1.3.6.1.2.1.2.2.1.10.2": 5000    # Interface 2 input - 5KB/s
        "1.3.6.1.2.1.2.2.1.16.2": 4500    # Interface 2 output - 4.5KB/s

  # Logging configuration
  logging:
    enabled: true
    level: info
    include_context_info: true  # Log SNMPv3 context information
    include_boundary_info: true # Log MIB boundary responses
    include_agentx_info: true   # Log AgentX simulation details

# REST API configuration
rest_api:
  enabled: true
  port: 8080
  
  # Enhanced monitoring endpoints
  enhanced_endpoints:
    agentx_status: true         # /api/agentx/status - subagent information
    context_management: true    # /api/contexts/* - context management
    boundary_stats: true       # /api/boundaries/stats - boundary condition stats

# WebSocket real-time monitoring
websocket:
  enabled: true
  
  channels:
    - name: "agentx-events"
      description: "AgentX subagent registration/disconnection events"
    - name: "context-access"
      description: "SNMPv3 context access attempts"
    - name: "boundary-responses"
      description: "MIB boundary condition responses"