# State Machine Configuration for Mock SNMP Agent
# This configuration enables device lifecycle simulation

simulation:
  behaviors:
    # Basic behaviors (can be combined with state machine)
    delay:
      enabled: false
    
    snmpv3_security:
      enabled: false

  # State Machine Configuration
  state_machine:
    enabled: true
    device_type: "router"          # router, switch, server, printer, generic
    initial_state: "booting"       # Starting state for the device
    auto_transitions: true         # Enable automatic state transitions
    
    # Transition timing configuration
    transition_delays:
      min: 5                       # Minimum seconds between transitions
      max: 30                      # Maximum seconds between transitions
    
    # Custom state definitions (optional - overrides defaults)
    custom_states:
      # Example: Custom operational state with specific characteristics
      custom_operational:
        description: "Custom operational state"
        duration_seconds: 600
        oid_availability: 100.0
        response_delay_ms: 25
        error_rate: 0.5
        next_states: ["maintenance", "degraded"]
        transition_probabilities:
          maintenance: 0.1
          degraded: 0.05
    
    # Global OID overrides for all states (optional)
    oid_overrides:
      "1.3.6.1.2.1.1.4.0": "State Machine Test Contact"  # sysContact
      "1.3.6.1.2.1.1.6.0": "State Machine Test Lab"      # sysLocation

  # Logging for state machine events
  logging:
    enabled: true
    level: "info"
    file: "logs/state_machine.log"
    format: "json"

  # REST API for state machine control
  rest_api:
    enabled: true
    host: "127.0.0.1"
    port: 8080